-- MySQL Script generated by MySQL Workbench
-- Sun Feb 17 17:28:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbminishop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbminishop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbminishop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbminishop` ;

-- -----------------------------------------------------
-- Table `dbminishop`.`danhmucsanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbminishop`.`danhmucsanpham` (
  `idDanhMucSanPham` INT(11) NOT NULL AUTO_INCREMENT,
  `tenDanhMuc` VARCHAR(50) NULL DEFAULT NULL,
  `hinhDanhMuc` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idDanhMucSanPham`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbminishop`.`sanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbminishop`.`sanpham` (
  `idSanPham` INT(11) NOT NULL AUTO_INCREMENT,
  `idDanhMucSanPham` INT(11) NULL DEFAULT NULL,
  `tenSanPham` VARCHAR(100) NULL DEFAULT NULL,
  `giaTien` INT(11) NULL DEFAULT NULL,
  `moTa` LONGTEXT NULL DEFAULT NULL,
  `hinhSanPham` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idSanPham`),
  INDEX `FK_danhmucsanpham_idx` (`idDanhMucSanPham` ASC) VISIBLE,
  CONSTRAINT `FK_danhmucsanpham`
    FOREIGN KEY (`idDanhMucSanPham`)
    REFERENCES `dbminishop`.`danhmucsanpham` (`idDanhMucSanPham`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 114
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbminishop`.`size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbminishop`.`size` (
  `idSize` INT(11) NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idSize`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbminishop`.`mausanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbminishop`.`mausanpham` (
  `idMauSanPham` INT(11) NOT NULL AUTO_INCREMENT,
  `mauSP` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idMauSanPham`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbminishop`.`chitietsanpham`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbminishop`.`chitietsanpham` (
  `idChiTietSanPham` INT(11) NOT NULL AUTO_INCREMENT,
  `idSanPham` INT(11) NULL DEFAULT NULL,
  `idSize` INT(11) NULL DEFAULT NULL,
  `idMauSanPham` INT(11) NULL DEFAULT NULL,
  `soLuong` INT(11) NULL DEFAULT NULL,
  `ngayNhap` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idChiTietSanPham`),
  INDEX `FK_sanpham_idx` (`idSanPham` ASC) VISIBLE,
  INDEX `FK_size_idx` (`idSize` ASC) VISIBLE,
  INDEX `Fk_mausanpham_idx` (`idMauSanPham` ASC) VISIBLE,
  CONSTRAINT `FK_sanpham`
    FOREIGN KEY (`idSanPham`)
    REFERENCES `dbminishop`.`sanpham` (`idSanPham`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_size`
    FOREIGN KEY (`idSize`)
    REFERENCES `dbminishop`.`size` (`idSize`),
  CONSTRAINT `Fk_mausanpham`
    FOREIGN KEY (`idMauSanPham`)
    REFERENCES `dbminishop`.`mausanpham` (`idMauSanPham`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbminishop`.`hoadon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbminishop`.`hoadon` (
  `idHoaDon` INT(11) NOT NULL AUTO_INCREMENT,
  `tenKhachHang` VARCHAR(50) NULL DEFAULT NULL,
  `soDT` VARCHAR(12) NULL DEFAULT NULL,
  `diaChiGiaoHang` VARCHAR(100) NULL DEFAULT NULL,
  `tinhTrang` VARCHAR(11) NULL DEFAULT NULL,
  `ngayMua` VARCHAR(10) NULL DEFAULT NULL,
  `hinhThucGiaoHang` VARCHAR(45) NULL DEFAULT NULL,
  `ghiChu` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idHoaDon`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbminishop`.`chitiethoadon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbminishop`.`chitiethoadon` (
  `idHoaDon` INT(11) NOT NULL,
  `idChiTietSanPham` INT(11) NOT NULL,
  `soLuong` INT(11) NULL DEFAULT NULL,
  `giaTien` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idHoaDon`, `idChiTietSanPham`),
  INDEX `FK_chitietsanpham_idx` (`idChiTietSanPham` ASC) VISIBLE,
  CONSTRAINT `FK_chitietsanpham`
    FOREIGN KEY (`idChiTietSanPham`)
    REFERENCES `dbminishop`.`chitietsanpham` (`idChiTietSanPham`),
  CONSTRAINT `FK_hoadon11`
    FOREIGN KEY (`idHoaDon`)
    REFERENCES `dbminishop`.`hoadon` (`idHoaDon`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbminishop`.`khuyenmai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbminishop`.`khuyenmai` (
  `idKhuyenMai` INT(11) NOT NULL AUTO_INCREMENT,
  `tenKhuyenMai` VARCHAR(50) NULL DEFAULT NULL,
  `thoiGianBatDau` VARCHAR(50) NULL DEFAULT NULL,
  `thoiGianKetThuc` VARCHAR(50) NULL DEFAULT NULL,
  `moTa` TEXT NULL DEFAULT NULL,
  `hinhKhuyenMai` TEXT NULL DEFAULT NULL,
  `giaGiam` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idKhuyenMai`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbminishop`.`chitietkhuyenmai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbminishop`.`chitietkhuyenmai` (
  `idKhuyenMai` INT(11) NOT NULL,
  `idSanPham` INT(11) NOT NULL,
  PRIMARY KEY (`idKhuyenMai`, `idSanPham`),
  INDEX `FK_sanpham_idx` (`idSanPham` ASC) VISIBLE,
  CONSTRAINT `FK_khuyenmai`
    FOREIGN KEY (`idKhuyenMai`)
    REFERENCES `dbminishop`.`khuyenmai` (`idKhuyenMai`),
  CONSTRAINT `FK_sanpham1`
    FOREIGN KEY (`idSanPham`)
    REFERENCES `dbminishop`.`sanpham` (`idSanPham`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbminishop`.`chucvu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbminishop`.`chucvu` (
  `idChucVu` INT(11) NOT NULL AUTO_INCREMENT,
  `tenChucVu` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`idChucVu`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = ascii;


-- -----------------------------------------------------
-- Table `dbminishop`.`nhanvien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbminishop`.`nhanvien` (
  `idNhanVien` INT(11) NOT NULL AUTO_INCREMENT,
  `hoTen` VARCHAR(50) NULL DEFAULT NULL,
  `diaChi` VARCHAR(100) NULL DEFAULT NULL,
  `gioiTinh` VARCHAR(4) NULL DEFAULT NULL,
  `cmnd` VARCHAR(20) NULL DEFAULT NULL,
  `soDT` INT(11) NULL DEFAULT NULL,
  `idChucVu` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `tenDangNhap` VARCHAR(20) NULL DEFAULT NULL,
  `matKhau` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idNhanVien`),
  INDEX `FK_chucvu_idx` (`idChucVu` ASC) VISIBLE,
  CONSTRAINT `FK_chucvu`
    FOREIGN KEY (`idChucVu`)
    REFERENCES `dbminishop`.`chucvu` (`idChucVu`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
